name: Build-Hardened-Loader
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install WDK
      run: choco install windows-driver-kit -y

    - name: Build Solution
      run: msbuild VmLoader.sln /p:Configuration=Release /p:Platform=x64

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: My-Custom-Loader
        path: |
          x64/Release/VmLoader.exe
          x64/Release/VmLoader.sys
