name: Build-Hardened-Loader
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Retarget and Build
      run: |
        
        msbuild VmLoader.sln /t:Retarget /p:Configuration=Release /p:Platform=x64

        msbuild VmLoader.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

    - name: Archive Results
      uses: actions/upload-artifact@v4
      with:
        name: Hardened-Loader
        path: |
          **\Release\VmLoader.exe
          **\Release\VmLoader.sys
