name: Build-Hardened-Loader
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install Missing Kernel Headers
      
      run: |
        choco install visualstudio2019-workload-vctools -y --no-progress

    - name: Build Solution
      
      run: msbuild VmLoader.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.19041.0

    - name: Archive Results
      uses: actions/upload-artifact@v4
      with:
        name: Hardened-Loader-Files
        path: |
          **/Release/*.exe
          **/Release/*.sys
